apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - imageName: slamdev/micro-ci-manual-runner
    docker:
      dockerfilePath: deploy/Dockerfile
      cacheFrom:
      - golang:alpine
      - alpine
      - slamdev/micro-ci-manual-runner
deploy:
  kustomize:
    kustomizePath: deploy
