apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - host: micro-ci.slamdev.net
    http:
      paths:
      - path: /
        backend:
          serviceName: web-ui-svc
          servicePort: 80
      - path: /api/
        backend:
          serviceName: api-gateway-svc
          servicePort: 80
