sudo: required

services:
- docker

before_install:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
- make build

branches:
  only:
  - master

notifications:
  email: false
