sudo: required

before_install:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- sudo add-apt-repository ppa:rmescandon/yq
- sudo apt update
- sudo apt install -y yq jq make
- curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && chmod +x skaffold && sudo mv skaffold /usr/local/bin

script:
- make build

branches:
  only:
  - master

notifications:
  email: false
