sudo: required

before_install:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
- make build

branches:
  only:
  - master

addons:
  apt:
    packages:
    - yq
    - jq
    - skaffold
    - kustomize

notifications:
  email: false
