[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/nats-io/go-nats"
  version = "1.5.0"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.2.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.5"

[[constraint]]
  name = "k8s.io/client-go"
  version = "8.0.0"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.0"
