apiVersion: v1
kind: Service
metadata:
  name: svc
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  github-integrator
      prefix: /api/github-integrator/
      service: github-integrator-svc
