apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - imageName: slamdev/micro-ci-web-ui
    docker:
      dockerfilePath: deploy/Dockerfile
      cacheFrom:
      - nginx:alpine
      - slamdev/micro-ci-web-ui
deploy:
  kustomize:
    kustomizePath: deploy
