apiVersion: v1
kind: Service
metadata:
  name: svc
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  manual-runner
      prefix: /api/manual-runner/
      service: manual-runner-svc
