apiVersion: v1
kind: Service
metadata:
  name: svc
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  pipeline-viewer
      prefix: /api/pipeline-viewer/
      service: pipeline-viewer-svc
